### ISSUE TITLE
AGP data example in git-lfs.

### ISSUE THREAD

**Issue by yu-zhang-oYo** [GPZ-Bioinfo/tmap_notebook#1]
I want to see AGP data example, but it is in git-lfs. When I use git lfs clone, it has the following error
"
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/GPZ-Bioinfo/tmap_notebook.git/info/lfs'
"
So if there is any other way to solve this?

**Comment by 444thLiao** [comment]
Sorry for that issue. Here is a temporary google drive link for the AGP data. 
[AGP dataset](https://drive.google.com/drive/folders/1pYhAmTT3ZNqAR-_ThIP5p9PUihhh1Ubq?usp=sharing)

It would be disabled in seven days.

**Comment by yu-zhang-oYo** [comment]
I appreciate for your kind help
